mqtt:
  host: 192.168.1.39
  port: 1883
#  doors: ["Garage1", "Garage2"]
  prefix: "garadget"
http:
  host: 192.168.1.37
  port: 8081
application:
  logLevel: info
  logLevelHttp: error
ssdp:
  enabled: false